### ISSUE TITLE
question about role control

### ISSUE THREAD

**Issue by falahatiali** [stalniy/casl-examples#10]
Thank you so much for your nice library. its so powerful I want to know why you dont have a clear way to controlling roles?

**Comment by stalniy** [comment]
What do you mean by "a clear way to controlling roles"?

There are 2 cookbook articles that explain how to use CASL for role based systems:
- https://casl.js.org/v4/en/cookbook/roles-with-persisted-permissions
- https://casl.js.org/v4/en/cookbook/roles-with-static-permissions

**Comment by stalniy** [comment]
Close as stale
