### ISSUE TITLE
Manage abilities already built on backend

### ISSUE THREAD

**Issue by francesco-clementi-92** [stalniy/casl-examples#11]
I'm building a react app with an express js server.

I correctly implemented CASL on the express js server and I'm trying to integrate casl on the react app.

With the login api I already have the abilities built by the express js server, so I have the following object:

`{permissions: {
O: {},
g: [{…}],
j: {User: {…}},
p: {},
s: false,
v: {}
}
}`

How can I integrate this in the react app?

**Comment by stalniy** [comment]
There is react-blog folder/example that integrates react app with express and casl
