### ISSUE TITLE
Getting `Cannot GET /session` when trying to log into the react blog

### ISSUE THREAD

**Issue by Jezfx** [stalniy/casl-examples#12]
Hi, 
Probably a user error somehow but trying to get the react blog set up. 
I've got the `blog-express` running (`3000`) and the db with the example Collection entries. 

However, when booting up the react-blog and trying to log in I'm getting this response: 
`Cannot GET /session`

I also get his when trying to access `http://localhost:3000/session` 

Is there something I'm missing, perhaps an Auth set up? Cheers

**Comment by stalniy** [comment]
Looking into [README of express-blog](https://github.com/stalniy/casl-examples/tree/master/packages/express-blog#instruction-to-login) I don't see `/session`. It should be `/api/session`

**Comment by Jezfx** [comment]
@stalniy thanks for getting back to me. You're right (sorry), and that endpoint worked and I managed to get the Token for it. But wasn't to get any of the other endpoints to work for me. 

It's fine though, I'll keep digging and find a work around. Will close this up. Cheers
