### ISSUE TITLE
Ability deprecated

### ISSUE THREAD

**Issue by memory660** [stalniy/casl-examples#17]
Ability is deprecated on Angular 15

**Comment by rafaelkachlon** [comment]
@stalniy, Hi, Ability class is deprecated, and when I try to provide createMongoAbility into Angular's app.module providers, I get the following error: `NullInjectorError: No provider for`.

Can you please provide an updated example for Angular?

**Comment by CynderR** [comment]
Same message with react and ts. Documentation is showing examples using Ability.

**Comment by berdejitendra14** [comment]
Any Updates on this issue.

The new documentation does not have clear instruction to implement CASL ability with new approach (createMongoAbility) in Angular 15. 
Also, the example is still using Ability and not createMongoAbility approach.

**Comment by stalniy** [comment]
Please read this thread meanwhile -> https://github.com/stalniy/casl/discussions/724 

and read JSDoc added to `Ability` class. The docs will be changed when v7 is released. `Ability` will be a part of library but it will serve a bit different purpose
