### ISSUE TITLE
📚 Add Next.js 13 Example to CASL Documentation

### ISSUE THREAD

**Issue by vrushank** [stalniy/casl-examples#19]
Hi 👋 

First of all, thank you for developing such an amazing library. I've been using CASL in my React projects, and now I'm migrating to a Next.js 13 project. While making the switch, I encountered some challenges in defining action & subject for a page/route. Afterwards, retrieving them in my server middleware and using `can` or some another way to redirect unauthorized or unauthenticated users to appropriate page.

I've gone through the documentation and examples you provided, but unfortunately, I couldn't find any guidance on how to integrate CASL with Next.js 13, particularly with server components and route protection.

I would greatly appreciate it if you could include a comprehensive example demonstrating how to implement CASL with Next.js 13 in the documentation. This addition would make it much smoother for developers like me to integrate CASL into their Next.js projects and benefit from its powerful features.

On a related note, since React now recommends using Next.js for new projects, this is an excellent opportunity to update the docs and replace React with Next.js in the CASL implementation guide. This update will make it more relevant and aligned with the latest trends in the frontend development ecosystem.

Looking forward to the Next.js 13 example and updated documentation!

Best Regards.

**Comment by stalniy** [comment]
Frankly speaking, I very low on free time. So, I will not work on this in the next year for sure. PRs as usually are very welcome.

**PS**: just my IMO, most of the SPAs don't need SSR. And it's cheaper/easier to use normal pre-rendering based. The main benefit of SSR is SEO, in this case you don't need prerender authorized/hidden by permissions pages at all. In case you think it speeds up how fast page is rendered, than SSR is not a silver bullet and has its own drawbacks, there are other simpler (frontend related) optimizations. So, I'd not use Next.js at all in 95% of projects

**Comment by vrushank** [comment]
Thanks for your answer. 👍🏻
