### ISSUE TITLE
Typescript Issue.

### ISSUE THREAD

**Issue by geekashu** [stalniy/casl-examples#4]
Hey, 

Is there an example which is not in typescript, simple javascript or JSX code (for react example)? I don't know typescript and would like to avoid the hassle to learn it for now.

I am not able to figure out how do I define this..

```
// Define what abilities different items can have.
const AppAbilities =
    ['read', 'Dashboard'] |
    ['read', 'AdminTools'] |
    ['create' | 'read' | 'update' | 'delete', 'UserInvite']
;

export const AppAbility = Ability(AppAbilities)
```

**Comment by geekashu** [comment]
I would also appreciate, if you can help me understand how can I update the rules on changes in redux store. 

I am trying to follow this example. https://dev.to/dwalsh01/managing-user-roles-in-react-using-casl-11f6

I think this is based on the older version of the casl.

Here is what I have done so far.

App.js
```
    // Play the magic of CASL RBAC. Update the roles if it changes.
    useEffect(() => {
        ability.update(defineRulesFor(userRoles));
    },[userRoles])
```

ability.js
```
import { AbilityBuilder, Ability, detectSubjectType, AbilityClass } from '@casl/ability';

// Defines how to detect object's type
function subjectName(item) {
    if (!item || typeof item === 'string') {
        return item;
    }
    return item.__type;
}
const ability = new Ability([], { subjectName });

export const defineRulesFor = (auth) => {
    console.log(auth);
    const { can, cannot, build } = new AbilityBuilder(Ability);

    can('view', 'all');
    can('view', 'ContainerHeader');
    return build();

    //
    // const { can, rules } = AbilityBuilder.extract();
    // if()
    //
    // if (auth.role === 'researcher') {
    //     can('view', 'Proposal', { userId: auth.user.id });
    //     can('view', 'Draft', { userId: auth.user.id });
    //     can('apply', 'Proposal', { userId: auth.user.id });
    //     can('view', 'Profile', { userId: auth.user.id });
    //     can('view', 'Teams', { userId: auth.user.id });
    // }
    // if (auth.role === 'admin') {
    //     can('add', 'Proposal', { userId: auth.user.id });
    //     can('view', 'Proposal', { userId: auth.user.id });
    //     can('accept', 'Application', { userId: auth.user.id });
    //     can('reject', 'Application', { userId: auth.user.id });
    //     can('view', 'PendingReviews', { userId: auth.user.id } )
    // }
    // if (auth.role === 'reviewer') {
    //     can('review', 'Proposal', { userId: auth.user.id });
    // }
    // return rules;
}

export default ability;

```

Can.js
```
// import { createCanBoundTo } from '@casl/react';
// import ability from './ability';
//
// export default createCanBoundTo(ability);


import { createContext } from 'react';
import { createContextualCan } from '@casl/react';

export const AbilityContext = createContext();
export const Can = createContextualCan(AbilityContext.Consumer);
```

AppLayout.js
```
            <AbilityContext.Provider value={ability}>
                <Routes/>
            </AbilityContext.Provider>
```

Dashboard.js
```
            <Can I="view" a="ContainerHeader">
                <ContainerHeader title={'Dashboard'} match={match}/>
            </Can>
```

But ContainerHeader component is never displayed. Please help.

Thanks

**Comment by stalniy** [comment]
> Hey,
> 
> Is there an example which is not in typescript, simple javascript or JSX code (for react example)? I don't know typescript and would like to avoid the hassle to learn it for now.
> 
> I am not able to figure out how do I define this..
> 
> ```
> // Define what abilities different items can have.
> const AppAbilities =
>     ['read', 'Dashboard'] |
>     ['read', 'AdminTools'] |
>     ['create' | 'read' | 'update' | 'delete', 'UserInvite']
> ;
> 
> export const AppAbility = Ability(AppAbilities)
> ```

You can try to use tsc and compile down the typescript example to ES6. I’ll check a bit later today whether I can add an npm script that can do this.

**Comment by stalniy** [comment]
Make sure that your `useEffect` works. The example from the article on dev.to should work even in latest CASL. 

PS: If you use react hooks, latest version of `@casl/react` provides `useAbility` hook which you can use to get access to `Ability` instance

**Comment by geekashu** [comment]
Thanks @stalniy , I got it working.

The change i had to make was this -

```
export const defineRulesFor = (auth) => {
    const { can, rules } = new AbilityBuilder(Ability);

    // Common Rules for all role
    can('read', 'Dashboard');

    // Rules specific to Admin role
    if (auth.includes("admin")) {
        can('read', 'AdminTools');
        can(['create', 'read', 'update', 'delete'], 'UserInvite');
    }

    // Rules specific to user role
    if (auth.includes("user")) {
        // Nothing for now
    }
    return rules;
}
```

Two things, i want to understand. 

1. I am using webstorm, and my IDE is giving the following warning, am I doing something wrong? 
![Screenshot 2020-05-09 12 42 15](https://user-images.githubusercontent.com/920804/81466958-12fef280-91f3-11ea-8cfa-d6c26704f46b.png)

2. How do I use useAbility hook? For now I am using the deafult export of the ability instance that I created in ability.js, and if I replace the same with `const ability = useAbility();` I start getting errors.

**Comment by stalniy** [comment]
1. Not sure why it shows this. I need to check this. Maybe for some reasons it tries to infer types using typescript and can’t do this properly
2. https://stalniy.github.io/casl/v4/en/package/casl-react Section about imperative access

**Comment by stalniy** [comment]
Added section that describes how to compile typescript sources to javascript sources and how to run them

**Comment by geekashu** [comment]
Excellent! Thanks a ton.
